#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config ignore_ewmh_focus true

bspc config focus_follows_pointer true
bspc config top_padding 38
bspc config pointer_modifier mod1

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Inkscape desktop='^6' follow=on

# bspc rule -a discord desktop='^4' follow=off
# bspc rule -a Discord desktop='^4' follow=off
bspc rule -a Zathura follow=on

#####################

# Kill if already running
killall -9 sxhkd xsettingsd dunst xfce4-power-manager polybar picom wluma nitrogen

# Lauch notification daemon
dunst &

pgrep -x sxhkd > /dev/null || sxhkd -c /home/john/.config/sxhkd/sxhkdrc &

# xsetroot -cursor_name left_ptr &

# Set keyboard layout
setxkbmap -option grp:alt_shift_toggle us,ru,ua &

# wluma &

nitrogen --restore &


exec polybar main -c $HOME/.config/polybar/config &
# polybar music &
# polybar other &
# polybar bspwm &

exec picom --backend glx --vsync --no-use-damage --experimental-backends &

# DISPLAY=:0 feh --bg-center --bg-fill $(find ~/Pictures/Backgrounds f | shuf -n 1)
feh --bg-center --bg-fill $(find ~/Pictures/Backgrounds f | shuf -n 1)

# discord &
