local knapsettings = {
  htmloutputext = "html",
  htmltohtml = "none",
  htmltohtmlviewerlaunch = "falkon %outputfile%",
  htmltohtmlviewerrefresh = "none",
  mdoutputext = "html",
  mdtohtml = "pandoc --standalone %docroot% -o %outputfile%",
  mdtohtmlviewerlaunch = "falkon %outputfile%",
  mdtohtmlviewerrefresh = "none",
  mdtopdf = "pandoc %docroot% -o %outputfile%",
  mdtopdfviewerlaunch = "sioyek %outputfile%",
  mdtopdfviewerrefresh = "none",
  markdownoutputext = "html",
  markdowntohtml = "pandoc --standalone %docroot% -o %outputfile%",
  markdowntohtmlviewerlaunch = "falkon %outputfile%",
  markdowntohtmlviewerrefresh = "none",
  markdowntopdf = "pandoc %docroot% -o %outputfile%",
  markdowntopdfviewerlaunch = "sioyek %outputfile%",
  markdowntopdfviewerrefresh = "none",
  texoutputext = "pdf",
  -- textopdf = "pdflatex -interaction=batchmode -halt-on-error -synctex=1 %docroot%",
  textopdf = "latexrun %docroot%",
  textopdfviewerlaunch = "sioyek --inverse-search 'nvim --headless -es --cmd \"lua require('\"'\"'knaphelper'\"'\"').relayjump('\"'\"'%servername%'\"'\"','\"'\"'%1'\"'\"',%2,%3)\"' --reuse-instance %outputfile%",
  textopdfviewerrefresh = "none",
  textopdfforwardjump = "sioyek --inverse-search 'nvim --headless -es --cmd \"lua require('\"'\"'knaphelper'\"'\"').relayjump('\"'\"'%servername%'\"'\"','\"'\"'%1'\"'\"',%2,%3)\"' --reuse-instance --forward-search-file %srcfile% --forward-search-line %line% %outputfile%",
  textopdfshorterror = "A=%outputfile% ; LOGFILE=\"${A%.pdf}.log\" ; rubber-info \"$LOGFILE\" 2>&1 | head -n 1",
  delay = 250
}

vim.g.knap_settings = knapsettings
